// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package srv

import (
	"minifast/app/pkg/options"
	"minifast/app/user/srv/controller/user"
	"minifast/app/user/srv/data/v1/db"
	"minifast/app/user/srv/service/v1"
	"minifast/gmicro/app"
	"minifast/pkg/log"
)

// Injectors from wire.go:

func initApp(logOptions *log.Options, serverOptions *options.ServerOptions, telemetryOptions *options.TelemetryOptions, mySQLOptions *options.MySQLOptions) (*app.App, error) {
	gormDB, err := db.GetDBFactoryOr(mySQLOptions)
	if err != nil {
		return nil, err
	}
	userStore := db.NewUsers(gormDB)
	userSrv := v1.NewUserService(userStore)
	userServer := user.NewUserServer(userSrv)
	server, err := NewUserRPCServer(telemetryOptions, serverOptions, userServer)
	if err != nil {
		return nil, err
	}
	appApp, err := NewUserApp(logOptions, serverOptions, server)
	if err != nil {
		return nil, err
	}
	return appApp, nil
}
